### ISSUE TITLE
Save Images: Unhandled Promise Rejection: TypeError (Safari/Firefox)

### ISSUE THREAD

**Issue by Yelles** [64robots/nova-image-cropper#13]
Hi,

A form with an Image Cropper Field can not be saved without changing image.

On Safari/Firefox (Chrome works fine)

JS Error Message:
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.t0.response.status')

Laravel Nova Image Field had the same issue (resolved now) : https://github.com/laravel/nova-issues/issues/378

**Comment by jBOKA** [comment]
The mentioned issue laravel/nova-issues#378 regarding the image field is not really solved, although closed. I still get it with v1.2.1

The exception looks exactly like this.

**Comment by Yelles** [comment]
> The mentioned issue [laravel/nova-issues#378](https://github.com/laravel/nova-issues/issues/378) regarding the image field is not really solved, although closed. I still get it with v1.2.1
> 
> The exception looks exactly like this.

are you sure, I see you've edited your post on the mentioned issue laravel/nova-issues#378

**Comment by disitec** [comment]
Applied fix by Nova File field. Please confirm this is fixed in 1.1.1.

**Comment by jBOKA** [comment]
@Yelles sorry, you're right. I had a third party problem... now everything works as expected.

**Comment by jBOKA** [comment]
> Applied fix by Nova File field. Please confirm this is fixed in 1.1.1.

@disitec see Yelles comment right before you. There's the commit including tag 1.1.1

**Comment by Yelles** [comment]
> Applied fix by Nova File field. Please confirm this is fixed in 1.1.1.

Hi, still not working :(

I have to Click on **Edit**, then **Done**. The save will work after that.

`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.t0.response.status')`

**Comment by michielfb** [comment]
> Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.t0.response.status')

I'm getting the same error in Firefox when editing a resource on `laravel/nova: v1.3.1` and `r64/nova-image-cropper:1.1.1`

**Comment by disitec** [comment]
Just pushed 1.1.2.

Can you try again @Yelles @michielfb

**Comment by michielfb** [comment]
@disitec Thanks! After I updated to 1.1.2 it now works as expected in Firefox.

**Comment by Yelles** [comment]
fully working, thanks again !
